### ISSUE TITLE
Sign Script should only show valid (unexpired) code signing certificates

### ISSUE THREAD

**Issue by patrichard** [jdhitsolutions/ISEScriptingGeek#12]
I noticed when I used the option that the pick list showed ALL code signing certs on my token - not just the valid one.

**Comment by jdhitsolutions** [comment]
I most likely wrote that code assuming a single certificate. Feel free to modify and submit a PR.

**Comment by patrichard** [comment]
For the completely clueless, like me, who are just now starting with github, do I just go to the file on the CODE tab, and then fork and edit?

**Comment by jdhitsolutions** [comment]
Yes. And remember this will only make you stronger.

**Comment by patrichard** [comment]
Hopefully I did it right….

**Comment by jdhitsolutions** [comment]
merged
