### ISSUE TITLE
Wish List/Feature Request

### ISSUE THREAD

**Issue by jdhitsolutions** [jdhitsolutions/ISEScriptingGeek#3]
Feel free to respond to this thread with any wish list or feature requests. I have these items on my wish list:
Add custom snippets
Add command to create a test self-signed certificate
Add a way to jump to different regions or sections like functions
Add a command to import a list of computers and create new remote powershell tab for each one

**Comment by artisticcheese** [comment]
1. Add ability to define "deployment" location for a file. Example being UNC or WebDav or FTP destination where development file shall be deployed to once you finished working with the file
2. Add ability to add/remove breakpoints by pressing on line number like all other major UIs do.

Thanks,
G

**Comment by jdhitsolutions** [comment]
The deployment idea is intriguing and some ideas come to mind. Finding time to work on them is something else. 
As for the breakpoints, if you are talking about clicking on that actual line number to the left, that is beyond the scope of ISE extensions. There is no way to implement anything like that. But the ISE has keyboard shortcuts under the Debug menu which should do the same thing. Press F9 to set a breakpoint on the current line. You don't even have to select the line, just position the cursor in the line.

**Comment by jdhitsolutions** [comment]
As VS Code is the direction going forward, I won't be doing much to improve this module..
