### ISSUE TITLE
New-DSCResourceSnippet.ps1 seems to break Show-command in PSH v5

### ISSUE THREAD

**Issue by JeffDykstra** [jdhitsolutions/ISEScriptingGeek#4]
Whenever I import the ISEScriptGeek module onto a windows 10 computer running PSH 5(5.0.10240.16384) show-command will no longer work. The inner exception is:
Unable to find type [Microsoft.PowerShell.DesiredStateConfiguration.DscResourceInfo]
If I comment out the import of new-dscreourcesnippet.ps1 the problem goes away.

Simple workaround is to add #requires -modules PSDesiredStateConfiguration in the new-dscresourcesnippet.ps1 script.

**Comment by jdhitsolutions** [comment]
Not too surprised. I have not tested much of the module at all in v5. I updated the file and you should see the change in the next update.
