### ISSUE TITLE
Need README for Clarity

### ISSUE THREAD

**Issue by michaeltlombardi** [jdhitsolutions/ISEScriptingGeek#5]
I actually stumbled across this repository from GitHub, not your blog - so trying to figure out what features this module brings and why I should care isn't immediately clear. I *did* check on your blog to get a better understanding, but even there I had to read a few different pages because you've added new features and updates.

It might be helpful to include a readme with an overview of the features and (maybe?) add to the wiki for the project, but I think the readme would be more immediately useful.

**Comment by jdhitsolutions** [comment]
No argument here. Documentation and major revisions are on the to do list.

**Comment by michaeltlombardi** [comment]
Fair enough. I've just grabbed a copy to poke around with. Maybe it'd be useful to organize some of the pages on the wiki as exports of the help sections/files? Synopsis might be fine for inclusion on the readme.

**Comment by jdhitsolutions** [comment]
Just a matter of finding some time after I pay the bills.

**Comment by michaeltlombardi** [comment]
I've got no problem submitting to the wiki for the help files if you want.

**Comment by jdhitsolutions** [comment]
This is an open project as far as I'm concerned so go ahead.

**Comment by dsolodow** [comment]
I've created a pull request with a first pass README.
