### ISSUE TITLE
Fatal error in New-CommentHelp.ps1, if no parameter names are provided.

### ISSUE THREAD

**Issue by bcdady** [jdhitsolutions/ISEScriptingGeek#7]
I had a previous edition of New-CommentHelp.ps1, (from an earlier download of the ISEScriptingGeek module, and had occasionally used New-CommentHelp (Alt+h in ISE) without specifying any parameters (e.g. for simple[r] functions). However, if/when I simply click [Enter], at the prompt "Enter a comma separated list of parameter names", the following PowerShell error text is displayed in the console:

```
Cannot index into a null array.
At ...\WindowsPowerShell\Modules\ISEScriptingGeek\New-CommentHelp.ps1:71 char:4
+    $aliases =    $command.parameters[$param].aliases
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Cannot index into a null array.
At ...\WindowsPowerShell\Modules\ISEScriptingGeek\New-CommentHelp.ps1:73 char:4
+    $pa = $command.parameters[$param].Attributes  | where {$_.GetType().name -eq  ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
```

**Comment by jdhitsolutions** [comment]
At first I'd think so what? If you don't specify parameters you should get an error. Then I realized you might have a command that takes no parameters. So yeah, I should take that into account.
