### ISSUE TITLE
Publish to the PowerShell Gallery

### ISSUE THREAD

**Issue by ryanwischkaemper** [jdhitsolutions/ISEScriptingGeek#9]
Publish this module to the [PowerShell Gallery](https://www.powershellgallery.com/) so that it can be installed via `Install-Module ISEScriptingGeek`

**Comment by jdhitsolutions** [comment]
I've thought about it. I feel so much is unfinished but perhaps that's just the way it is. Let me look into it.

**Comment by jdhitsolutions** [comment]
This is now published to the PowerShell Gallery.
